[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

[functions]
  external_node_modules = ["express", "openai", "@anthropic-ai/sdk", "@google/generative-ai"]
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[functions.server]
  external_node_modules = ["express", "openai", "@anthropic-ai/sdk", "@google/generative-ai"]
  node_bundler = "esbuild"

[build.processing]
  skip_processing = false

[build.processing.js]
  bundle = true
  minify = true

[dev]
  framework = "vite"
  targetPort = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 