[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[functions]
  external_node_modules = ["express", "openai", "@anthropic-ai/sdk", "@google/generative-ai"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 